export const periodTypes = [
    'DAILY',
    'WEEKLY',
    'WEEKLYMON',
    'WEEKLYTUE',
    'WEEKLYWED',
    'WEEKLYTHU',
    'WEEKLYFRI',
    'WEEKLYSAT',
    'WEEKLYSUN',
    'BIWEEKLY',
    'MONTHLY',
    'BIMONTHLY',
    'QUARTERLY',
    'QUARTERLYJAN',
    'QUARTERLYFEB',
    'QUARTERLYMAR',
    'QUARTERLYAPR',
    'QUARTERLYMAY',
    'QUARTERLYJUN',
    'QUARTERLYJUL',
    'QUARTERLYAUG',
    'QUARTERLYSEP',
    'QUARTERLYOCT',
    'QUARTERLYNOV',
    'QUARTERLYDEC',
    'SIXMONTHLY',
    'SIXMONTHLYJAN',
    'SIXMONTHLYFEB',
    'SIXMONTHLYMAR',
    'SIXMONTHLYAPR',
    'SIXMONTHLYMAY',
    'SIXMONTHLYJUN',
    'SIXMONTHLYJUL',
    'SIXMONTHLYAUG',
    'SIXMONTHLYSEP',
    'SIXMONTHLYOCT',
    'SIXMONTHLYNOV',
    'SIXMONTHLYDEC',
    'YEARLY',
    'FYJAN',
    'FYFEB',
    'FYMAR',
    'FYAPR',
    'FYMAY',
    'FYJUN',
    'FYJUL',
    'FYAUG',
    'FYSEP',
    'FYOCT',
    'FYNOV',
    'FYDEC',
] as const

/*
 * The relative period types are obtained from the analytics package only applicable for relative periods
 * https://github.com/dhis2/analytics/blob/master/src/components/PeriodDimension/utils/index.js
 * */
export const relativePeriodTypes = [
    'DAILY',
    'WEEKLY',
    'WEEKS_THIS_YEAR',
    'BIWEEKLY',
    'MONTHLY',
    'BIMONTHLY',
    'QUARTERLY',
    'SIXMONTHLY',
    'FINANCIAL',
    'YEARLY',
] as const
